name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: feature_a
    steps:
      - name: deploy
        run: echo "$TENANT"
      - name: deploy 2
        run: echo "${{ github.ref }}"
